// components/chips/FameChip.tsx
import { Chip } from '@heroui/react';
import { Fame } from '@/types/Sheet';

export default function FameChip({ fame }: { fame: Fame }) {
  return (
    <Chip
      size="md"
      variant="flat"
      classNames={{
        base: `bg-${fame?.color ?? 'white'}`,
        content: `text-${fame?.text ?? 'black'}`,
      }}
    >
      {fame?.label}
    </Chip>
  );
}

// src/components/theme/FameChip.vue
<template>
  <q-chip
    v-if="props.fame"
    size="md"
    :label="props.fame.label"
    :class="`bg-${props.fame.color ?? 'white'} text-${props.fame.text ?? 'black'}`"
  />
</template>

<script setup lang="ts">
import type { Fame } from 'src/types/Sheet'

const props = defineProps<{
  fame: Fame
}>()
</script>
