// components/grade/GradeChip.tsx
import { Chip } from "@nextui-org/react"
import { MapGrade } from "@/types/Sheet"

export default function GradeChip({ grade }: { grade: MapGrade}) {
  return (
    <Chip
      size="md"
      variant="solid"
      classNames={{
        base: `bg-${grade?.background ?? "white"}`,
        content: `text-${grade?.text ?? "black"}`,
      }}
    >
      {grade?.label}
    </Chip>
  )
}

// src/components/theme/GradeChip.vue
<template>
  <q-chip
    size="md"
    :label="props.grade.label"
    :class="`bg-${props.grade.background ?? 'white'} text-${props.grade.text ?? 'black'}`"
  />
</template>

<script setup lang="ts">
import type { MapGrade } from 'src/types/Sheet'

const props = defineProps<{
  grade: MapGrade
}>()
</script>
